import React from "react";
import { Link } from "react-router-dom";
import "@fortawesome/fontawesome-free/css/all.css";

const Services = () => {
  // Define the servicesData array
  const servicesData = [
    {
      id: 1,
      name: "Stage 1 Tuning",
      shortDescription: "Optimise performance via ECU software modifications.",
      description:
        "Stage 1 tuning typically involves software modifications to the engine control unit (ECU) to optimise performance without significant hardware changes. This may include adjustments to fuel maps, ignition timing, and boost pressure to increase power and torque output within safe limits.",
      iconClass: "fas fa-cogs",
    },
    {
      id: 2,
      name: "Stage 2 Tuning",
      shortDescription:
        "Enhanced performance with additional hardware and software modifications.",
      description:
        "Stage 2 tuning usually builds upon Stage 1 by incorporating additional hardware modifications, such as upgraded intake and exhaust systems, intercoolers, and turbochargers. This allows for more aggressive tuning and higher power gains compared to Stage 1.",
      iconClass: "fas fa-tachometer-alt",
    },
    {
      id: 3,
      name: "Eco Tuning",
      shortDescription:
        "Improve fuel efficiency and reduce emissions through engine optimisation.",
      description:
        "Eco tuning focuses on optimising engine parameters to improve fuel efficiency and reduce emissions, often through adjustments to fuel mapping, air-to-fuel ratios, and other variables. This can help achieve better mileage and lower environmental impact.",
      iconClass: "fas fa-leaf",
    },
    {
      id: 4,
      name: "Adblue Delete",
      shortDescription: "Increase performance by removing Adblue system.",
      description:
        "Adblue is a urea-based solution used in modern diesel engines to reduce nitrogen oxide emissions. Adblue delete involves disabling or removing the Adblue system, which can lead to increased emissions and may not comply with environmental regulations.",
      iconClass: "fas fa-times-circle",
    },
    {
      id: 5,
      name: "DPF Delete",
      shortDescription: "Boost engine performance by removing DPF filter.",
      description:
        "DPF (Diesel Particulate Filter) traps particulate matter from the exhaust to reduce emissions. DPF delete involves removing or bypassing this filter, which can improve engine performance but may result in higher emissions and legal issues in regions with emission standards.",
      iconClass: "fas fa-filter",
    },
    {
      id: 6,
      name: "EGR Delete",
      shortDescription: "Enhance engine performance by removing EGR system.",
      description:
        "The Exhaust Gas Recirculation system reduces nitrogen oxide emissions by recirculating a portion of exhaust gas into the engine's intake. EGR delete involves disabling or removing this system, which can improve performance but may increase emissions and cause legal issues in some areas.",
      iconClass: "fas fa-ban",
    },
    {
      id: 7,
      name: "P Code Deletes",
      shortDescription: "Suppress diagnostic trouble codes to prevent errors.",
      description:
        "P codes are diagnostic trouble codes generated by the vehicle's onboard diagnostics system to indicate faults or issues. Deleting P codes involves suppressing or disabling certain codes, often done during tuning or modification processes to prevent warning lights or error messages.",
      iconClass: "fas fa-code",
    },
    {
      id: 8,
      name: "Swirl Flap Delete",
      shortDescription:
        "Improve combustion efficiency by removing swirl flaps.",
      description:
        "Swirl flaps are devices in the intake manifold that improve air swirl for better combustion efficiency at low engine speeds. Deleting swirl flaps involves removing or disabling these devices, which can impact low-end torque and emissions performance.",
      iconClass: "fas fa-wind",
    },
    {
      id: 9,
      name: "Lambda Delete",
      shortDescription:
        "Disrupt lambda sensors (oxygen sensors) to alter fuel mixture.",
      description:
        "Lambda sensors (oxygen sensors) measure oxygen content in the exhaust gases to adjust fuel mixture. Deleting lambda sensors involves removing or bypassing these sensors, but it can disrupt fueling and emissions control, leading to poor performance and increased emissions.",
      iconClass: "fas fa-fire",
    },
    {
      id: 10,
      name: "MAF Delete",
      shortDescription: "Improve air-fuel ratio by removing MAF sensor.",
      description:
        "MAF (Mass Air Flow) sensor measures the amount of air entering the engine and is crucial for fuel metering. MAF delete involves removing or bypassing this sensor, but it can disrupt air-fuel ratio calculations and potentially cause drivability issues.",
      iconClass: "fas fa-wind",
    },
    {
      id: 11,
      name: "ECU Cloning",
      shortDescription: "Copy ECU data for engine swaps or replacements.",
      description:
        "ECU cloning involves copying the software and data from one ECU to another, typically for purposes such as engine swaps or replacements. It ensures that the replacement ECU has the same programming and configuration as the original.",
      iconClass: "fas fa-copy",
    },
    {
      id: 12,
      name: "Need Help?",
      shortDescription:
        "Got a question about any of our services? Contact us here.",
      iconClass: "fas fa-question-circle",
    },
  ];

  return (
    <div>
      <section className="section services-section" id="services">
        <div className="container">
          <div className="row">
            <div className="col-lg-6">
              <div className="section-title">
                <h2>
                  <span style={{ color: "#20257B" }}>Services We Offer</span>
                </h2>
              </div>
            </div>
          </div>
          <div className="row">
            {servicesData.map((service) => (
              <div className="col-sm-6 col-lg-4" key={service.id}>
                <div className="feature-box-1">
                  <div className="icon">
                    <i
                      className={service.iconClass}
                      style={{
                        color: "#20257B",
                        paddingRight: "5px",
                        paddingLeft: "5px",
                      }}
                    />
                  </div>
                  <div className="feature-content px-2 py-1">
                    <h5>{service.name}</h5>
                    <p className="pb-1">{service.shortDescription}</p>
                    {/* Conditionally render Link for the "Need Help?" service */}
                    {service.id === 12 ? (
                      <Link to="/contact">Learn More</Link>
                    ) : (
                      <Link
                        to={{
                          pathname: `/individual-service/${service.id}`,
                          state: { service: servicesData },
                        }}
                      >
                        Learn More
                      </Link>
                    )}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>
    </div>
  );
};

export default Services;
